package hxd;

import haxe.Int64;

import hxd.Key.KeyCode;

enum EventKind {
	EPush;
	ERelease;
	EMove;
	EOver;
	EOut;
	EWheel;
	EFocus;
	EFocusLost;
	EKeyDown;
	EKeyUp;
	EReleaseOutside;
	ETextInput;
	/**
		Used to check if we are still on the interactive if no EMove was triggered this frame.
	**/
	ECheck;
}

class Event {

	public var kind : EventKind;
	public var relX : Float;
	public var relY : Float;
	public var relZ : Float;
	/**
		Will propagate the event to other interactives that are below the current one.
	**/
	public var propagate : Bool;
	/**
		Will cancel the default behavior for this event as if it had happen outside of the interactive zone.
	**/
	public var cancel : Bool;
	public var button : Int = 0;
	public var touchId : Int;
	public var keyCode : KeyCode;
	public var charCode : Int;
	public var wheelDelta : Float;
	/**
		Monotonic timestamp when the native event occurred, in nanoseconds.

		Native backends that do not provide event timestamps leave this at 0.
	**/
	public var timestamp : Int64 = 0;
	/**
		Convenience conversion for display and simple gameplay use.

		For precise timing differences, subtract Int64 nanosecond timestamps first,
		then convert the resulting delta to milliseconds.
	**/
	public var timestampMs(get, never) : Float;
	/**
		True when this keyboard event was generated by native key repeat.
	**/
	public var isRepeat : Bool = false;

	public function new(k,x=0.,y=0.) {
		kind = k;
		this.relX = x;
		this.relY = y;
	}

	private inline function get_timestampMs() : Float {
		return timestamp.toFloat() / 1_000_000.0;
	}

	public function toString() {
		return kind + "[" + Std.int(relX) + "," + Std.int(relY) + "]" + switch( kind ) {
		case EPush, ERelease, EReleaseOutside: ",button=" + button;
		case EMove, EOver, EOut, EFocus, EFocusLost, ECheck: "";
		case EWheel: ",wheelDelta=" + wheelDelta;
		case EKeyDown, EKeyUp: ",keyCode=" + keyCode;
		case ETextInput: ",charCode=" + charCode;
		}
	}

}
